### ISSUE TITLE
Raspberry Pi Installation

### ISSUE THREAD

**Issue by cbradburne** [YCSRobotics/GrizzlyTime#10]
**Describe the bug**
Can't get GrizzlyTime-2.3.0 to run on Raspberry Pi

**To Reproduce**
A fresh Rasbian installation on a RPi 4. 
Installed Java with "sudo apt install default-jdk"
Run "java -jar GrizzlyTime-2.3.0-Java11.jar"
See log below.

**Expected behavior**
GrizzlyTime-2.3.0 to run

**Log File**
OpenJDK Server VM warning: You have loaded library /home/pi/.openjfx/cache/11.0.2/libprism_es2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/11.0.2/libprism_es2.so: /home/pi/.openjfx/cache/11.0.2/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/11.0.2/libprism_es2.so: /home/pi/.openjfx/cache/11.0.2/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
at java.base/java.lang.Runtime.load0(Runtime.java:768)
at java.base/java.lang.System.load(System.java:1837)
at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:315)
at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
at java.base/java.lang.Thread.run(Thread.java:834)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/11.0.2/libprism_sw.so: /home/pi/.openjfx/cache/11.0.2/libprism_sw.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/11.0.2/libprism_sw.so: /home/pi/.openjfx/cache/11.0.2/libprism_sw.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
at java.base/java.lang.Runtime.load0(Runtime.java:768)
at java.base/java.lang.System.load(System.java:1837)
at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:315)
at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
at java.base/java.lang.Thread.run(Thread.java:834)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
at java.base/java.lang.Thread.run(Thread.java:834)

**Desktop (please complete the following information):**
Raspbian GNU/Linux 10

**Comment by Daltz333** [comment]
Can you try installing openjdk instead?

**Comment by Daltz333** [comment]
Thats a new one. Give me a bit to do some investigation. You have a display server setup right? And your using the full version of Raspbian, not the lite version?

**Comment by Daltz333** [comment]
You could also try using the bellsoft Java.

**Comment by cbradburne** [comment]
Full version with a screen.
I'll give bellsoft Java a look into.  I really appreciate your help. Covid restrictions mean we have a different exit door to the entrance door so our usual in/out board is of no use. Trying to set up 2(or more) raspberries, one at each door. 
Thanks!!

**Comment by cbradburne** [comment]
ooh you're a star!! Almost there. I can get all the way to the main screen, but it only shows a small center section of the app.

**Comment by Daltz333** [comment]
Small center section of the app, hmmm. Is your display resolution set correctly? Additionally, you can try pressing "escape" or the "f11" key. What size is your display?

**Comment by cbradburne** [comment]
![Screenshot 2020-09-25 at 18 14 12](https://user-images.githubusercontent.com/2190423/94296592-fd4c5880-ff5a-11ea-9fbb-88d36808aa6c.png)
This is after I've pressed F11

800x480 resolution

**Comment by Daltz333** [comment]
What's the normal look like?

**Comment by cbradburne** [comment]
[Raspi.mp4.zip](https://github.com/YCSRobotics/GrizzlyTime/files/5284692/Raspi.mp4.zip)
Here's the entire process in a screencast.

Loading,
Press F11,
Press escape.

**Comment by Daltz333** [comment]
I'm. Very weird. Does this change with a different/higher resolution monitor? I've only tested with an RPi3

**Comment by cbradburne** [comment]
[Grizzly-maximise.mp4.zip](https://github.com/YCSRobotics/GrizzlyTime/files/5285721/Grizzly-maximise.mp4.zip)

ok, so, it looks like I can resize the first splash screen, and that re-sizing does seem to carry over to the main screen. I just can't change the size when it gets to the main screen. Still doesn't allow fullscreen.
[grizzly-FS2.mp4.zip](https://github.com/YCSRobotics/GrizzlyTime/files/5285717/grizzly-FS2.mp4.zip)

**Comment by Daltz333** [comment]
The fullscreen issue is a known bug for Linux. Not sure exactly why.

**Comment by cbradburne** [comment]
After lots of trial and error (my lack of knowledge) I've managed to compile your code myself. In Constants.java I've changed:
//window constants
    public static final boolean kWindowResizable = false;

to

//window constants
    public static final boolean kWindowResizable = true;

This enables fullscreen.
[Grizzly Fullscreen.mp4.zip](https://github.com/YCSRobotics/GrizzlyTime/files/5286722/Grizzly.Fullscreen.mp4.zip)

**Comment by Daltz333** [comment]
Interesting. I had locked the screen resize ability previously as it can cause funky behavior when resizing. So the fullscreen works as intended with that patch? Is the normal minimized view working fine?

**Comment by cbradburne** [comment]
Other than a few bits being hidden due to the low resolution screen I'm using, yes. The app centers every time I resize the app, and the app keeps working.

The only odd behaviour, is that the opening splash screen is blank (white). I doubt it's related but you never know. It's always been white on Raspbian, even before I started messing around :)

**Comment by Daltz333** [comment]
Yeah, that's a Linux specific thing. I suspect the image isn't being displayed right in the pathing. Works fine on windows.

**Comment by cbradburne** [comment]
I've just compiled for MacOS and Windows with kWindowResizable = true;
All working fine, MacOS 10.15.7 (latest current release) and Windows 10.

There's no splash screen at all on MacOS. Windows splash screen is just white. I'll have a look in to the splash screen, but it doesn't stop the functionality.

Note, this is all tested with Java11

**Comment by memtech3** [comment]
are there any updates to this issue? 5892 wants to use GrizzlyTime on a pi for this season

**Comment by Daltz333** [comment]
You can use the workarounds listed above. It also does work, but full screen can be a bit funky. @prateekma used on a RPi AFAIK

Edit: Asked him via discord and it did work on RPi with fullscreen

**Comment by memtech3** [comment]
Thanks!
